stages:
  - compile
  - test
  - build-container
  - review
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

  REPO_NAME: gitlab.com/$CI_PROJECT_PATH
  DOCKER_IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH

  MR_ID: $CI_MERGE_REQUEST_IID
  OKTETO_PREVIEW_NS: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
  TAG: $CI_COMMIT_SHORT_SHA

.go:
  image: $GO_IMAGE
  variables:
    GO_IMAGE: golang:1.16-alpine3.14
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    GOPATH: /go
    REPO_NAME: $CI_SERVER_HOST/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  cache:
    key: ${CI_COMMIT_REF_NAME}
    when: on_success
    paths:
      - $GOPATH
      - $CI_PROJECT_DIR/vendor
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go mod download

.master-and-mr-rules:
  only:
    - $CI_DEFAULT_BRANCH
    - merge_requests

compile:
  stage: compile
  extends:
    - .go
    - .master-and-mr-rules
  variables:
    OUTPUT_FILE: main
  script:
    - go build -o $OUTPUT_FILE
  artifacts:
    paths:
      - $OUTPUT_FILE

test:
  stage: test
  needs: []
  extends:
    - .go
    - .master-and-mr-rules
  variables:
    GO_IMAGE: golang:1.16
  script:
    - go get gotest.tools/gotestsum
    - go get github.com/boumenot/gocover-cobertura

    # test report
    - gotestsum --junitfile report.xml --format testname

    # coverage
    - go test -coverprofile=coverage.txt -covermode count ./...
    - gocover-cobertura < coverage.txt > coverage.xml

    # upload to codecov
    - curl -s https://codecov.io/bash | bash - || true

    # display from coverage.txt
    - go tool cover -func=coverage.txt
  coverage: '/total:.*\d+.\d+%/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml

build-container-okteto:
  stage: build-container
  extends:
    - .master-and-mr-rules
  image: docker:19
  services:
    - docker:19-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG:$TAG -f ci.Dockerfile .
    - docker push $DOCKER_IMAGE_TAG:$TAG
    - docker logout $CI_REGISTRY
  dependencies:
    - compile

review:
  stage: review
  image: okteto/okteto:1.13.4
  variables:
    APP: $OKTETO_PREVIEW_NS
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - |
      okteto preview deploy $OKTETO_PREVIEW_NS \
      --scope personal \
      --branch $CI_COMMIT_REF_NAME \
      --repository $CI_REPOSITORY_URL \
      --var TAG=$TAG
    - sleep 10
    - |
      kubectl get secret loki --namespace=$CI_PROJECT_ROOT_NAMESPACE -o yaml \
      | sed "s/namespace: $CI_PROJECT_ROOT_NAMESPACE/namespace: $OKTETO_PREVIEW_NS/" \
      | kubectl create --namespace=$OKTETO_PREVIEW_NS -f - || true
    - |
      kubectl get configmap cjtim-backend-go-configmap --namespace=$CI_PROJECT_ROOT_NAMESPACE -o yaml \
      | sed "s/namespace: $CI_PROJECT_ROOT_NAMESPACE/namespace: $OKTETO_PREVIEW_NS/" \
      | kubectl create --namespace=$OKTETO_PREVIEW_NS -f - || true
  environment:
    name: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
    url: "https://cjtim-backend-go-mr-$CI_MERGE_REQUEST_IID-$CI_PROJECT_ROOT_NAMESPACE.cloud.okteto.net"
    on_stop: stop-review
  only:
    - merge_requests

stop-review:
  stage: review
  image: okteto/okteto:1.13.4
  when: manual
  environment:
    name: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
    action: stop
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - okteto preview destroy ${OKTETO_PREVIEW_NS}
  variables:
    GIT_STRATEGY: none
  only:
    - merge_requests

okteto:
  stage: deploy
  needs:
    - build-container-okteto
  image: okteto/okteto:1.13.4
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - sed -e "s/TAG/$TAG/" k8s/deployment.yaml | kubectl apply -f -
    - kubectl apply -f k8s/service.yaml
  only:
    - $CI_DEFAULT_BRANCH
