stages:
  - compile
  - test
  - build-container
  - review
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

  REPO_NAME: gitlab.com/$CI_PROJECT_PATH
  DOCKER_IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH

  MR_ID: $CI_MERGE_REQUEST_IID
  OKTETO_PREVIEW_NS: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
  TAG: $CI_COMMIT_SHORT_SHA

.go:
  image: golang:1.16-alpine3.14
  variables:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
    GOPATH: $CI_PROJECT_DIR/.cache
  cache:
    key: $CI_JOB_NAME
    when: always
    paths:
      - $GOPATH
  before_script:
    - mkdir -p .cache
    - go mod download

compile:
  stage: compile
  extends: .go
  variables:
    OUTPUT_FILE: main
  script:
    - go build -o $OUTPUT_FILE
  artifacts:
    paths:
      - $OUTPUT_FILE
  rules: &ci_rule
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:
  stage: test
  image: golang:1.16-alpine3.14
  script:
    - apk add --no-cache gcc musl-dev
    # test report
    - go get gotest.tools/gotestsum
    - gotestsum --junitfile report.xml --format testname
    # coverage
    - go get github.com/boumenot/gocover-cobertura
    - go test -coverprofile=coverage.txt -covermode count ./...
    - gocover-cobertura < coverage.txt > coverage.xml
  after_script:
    - bash <(curl -s https://codecov.io/bash)
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs: []
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml

build-container-okteto:
  stage: build-container
  image: docker:19
  services:
    - docker:19-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG:$TAG -f ci.Dockerfile .
    - docker push $DOCKER_IMAGE_TAG:$TAG
    - docker logout $CI_REGISTRY
  dependencies:
    - compile
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

review:
  stage: review
  image: okteto/okteto:1.13.4
  variables:
    APP: $OKTETO_PREVIEW_NS
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - |
      okteto preview deploy $OKTETO_PREVIEW_NS \
      --scope personal \
      --branch $CI_COMMIT_REF_NAME \
      --repository $CI_REPOSITORY_URL \
      --var TAG=$TAG
    - sleep 10
    - |
      kubectl get secret loki --namespace=$CI_PROJECT_ROOT_NAMESPACE -o yaml \
      | sed "s/namespace: $CI_PROJECT_ROOT_NAMESPACE/namespace: $OKTETO_PREVIEW_NS/" \
      | kubectl create --namespace=$OKTETO_PREVIEW_NS -f - || true
    - |
      kubectl get configmap cjtim-backend-go-configmap --namespace=$CI_PROJECT_ROOT_NAMESPACE -o yaml \
      | sed "s/namespace: $CI_PROJECT_ROOT_NAMESPACE/namespace: $OKTETO_PREVIEW_NS/" \
      | kubectl create --namespace=$OKTETO_PREVIEW_NS -f - || true
  environment:
    name: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
    url: "https://cjtim-backend-go-mr-$CI_MERGE_REQUEST_IID-$CI_PROJECT_ROOT_NAMESPACE.cloud.okteto.net"
    on_stop: stop-review
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stop-review:
  stage: review
  image: okteto/okteto:1.13.4
  when: manual
  environment:
    name: "mr-${CI_MERGE_REQUEST_IID}-${CI_PROJECT_ROOT_NAMESPACE}"
    action: stop
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - okteto preview destroy ${OKTETO_PREVIEW_NS}
  variables:
    GIT_STRATEGY: none
  only:
    - merge_requests

okteto:
  stage: deploy
  needs:
    - build-container-okteto
  image: okteto/okteto:1.13.4
  script:
    - export OKTETO_TOKEN=$(echo $OKTETO_TOKEN | base64 -d)
    - okteto namespace
    - sed -e "s/TAG/$TAG/" k8s/deployment.yaml | kubectl apply -f -
    - kubectl apply -f k8s/service.yaml
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
