# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: "windows"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=off
    goos:
      - windows
    main: cmd/cjtim-backend-go/main.go

  - id: "linux_and_darwin"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: cmd/cjtim-backend-go/main.go
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
