steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
  - '-c'
  - "gcloud secrets versions access latest --secret=cjtim-backend-go_serviceAcc --format='get(payload.data)' | tr '_-' '/+' | base64 -d > serviceAcc.json"
# Build
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
  - '.'
# Push
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - '$REPO_NAME-$BRANCH_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA'