steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=cjtim-backend-go_serviceAcc --format='get(payload.data)' | tr '_-' '/+' | base64 -d > serviceAcc.json && \
        gcloud secrets versions access latest --secret=cjtim-backend-go_env --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env
  # Test
  - name: "golang"
    args: ["go", "get", "-d", "-v"]
  - name: "golang"
    args: ["go", "get", "github.com/joho/godotenv/cmd/godotenv"]
  - name: "golang"
    args: ["godotenv", "go", "test", "-v", "./..."]
  - name: "golang"
    args: ["rm", "-rf", ".env"]
  # Build
  - name: "golang"
    args: ["go", "build", "-o", "./main"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
      - "-f"
      - "ci.Dockerfile"
      - "."
  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME-$BRANCH_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
options:
  volumes:
    - name: go-modules
      path: /go
  env:
    - GO111MODULE=on
