steps:
  # Test
  - name: "golang"
    args: ["go", "get", "-d", "-v"]
  # - name: "golang"
  #   args: ["go", "test", "-v", "./..."]
  # Build
  - name: "golang"
    args: ["go", "build", "-o", "./main"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
      - "-f"
      - "ci.Dockerfile"
      - "."
  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
  # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME-$BRANCH_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME:$SHORT_SHA"
options:
  volumes:
    - name: go-modules
      path: /go
  env:
    - GO111MODULE=on
