replicaCount: 2

image:
  repository: registry.gitlab.com/cjtim/cjtim-backend-go
  pullPolicy: IfNotPresent

service:
  name: cjtim-backend-go
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  MONGO_URI: "mongodb+srv://mongodb:IOusITrIdINkHatiaNs@cluster0.ejncx.mongodb.net/admin?authSource=admin&replicaSet=atlas-4l0s1w-shard-0&readPreference=primary&ssl=true"
