apiVersion: apps/v1
kind: Deployment
metadata:
  name: cjtim-backend-go
spec:
  selector:
    matchLabels:
      app: cjtim-backend-go
  replicas: 1
  template:
    metadata:
      labels:
        app: cjtim-backend-go
    spec:
      containers:
        # Logging agent
        - name: fluentd
          image: grafana/fluent-plugin-loki:master
          env:
            - name: 'APP_NAME'
              value: "cjtim-backend-go"
          command:
            [
              "fluentd",
              "-c",
              "/fluentd/etc/fluent.conf",
              "-p",
              "/fluentd/plugins",
              "--under-supervisor",
            ]
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: config-volume
              mountPath: /fluentd/etc
        # Application
        - name: cjtim-backend-go
          # TAG will be replace during Gitlab CI pipeline
          image: registry.cloud.okteto.net/NS/cjtim-backend-go:TAG
          envFrom:
            - configMapRef:
                name: cjtim-backend-go-configmap
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            httpGet:
              path: /health
              port: 8080
          volumeMounts:
            - name: varlog
              mountPath: /var/log

      volumes:
        - name: config-volume
          configMap:
            name: cjtim-backend-go-configmap
        - name: varlog
          emptyDir: {}
