apiVersion: apps/v1
kind: Deployment
metadata:
  name: cjtim-backend-go
spec:
  selector:
    matchLabels:
      app: cjtim-backend-go
  replicas: 1
  template:
    metadata:
      labels:
        app: cjtim-backend-go
    spec:
      containers:
        - name: cjtim-backend-go
          image: registry.cloud.okteto.net/cjtim/cjtim-backend-go:$(TAG)
          envFrom:
            - configMapRef:
                name: cjtim-backend-go-configmap
          resources:
            limits:
              cpu: 800m
              memory: 256Mi
          ports:
            - containerPort: 8080
