version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  # setup:
  #   image: mongo:4.4.6
  #   depends_on:
  #     - mongodb
  #   restart: "no"
  #   volumes:
  #     - ./initdb.js:/initdb.js
  #   entrypoint: ["bash", "-c", "sleep 5 && mongo --nodb /initdb.js && exit"]

  redis:
    image: redis:6.2-alpine
  app:
    depends_on:
      # - setup
      - redis
    env_file: ../.env
    build: 
      context: ..
      dockerfile: tools/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../configs/serviceAcc.json:/root/configs/serviceAcc.json
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb:mongodb@mongodb
      MONGO_DB: production
